## Dimensionality  Reduction

In [1]:
### How to  eliminate the couple of features from  the trainning set and analyze the data set the probably
  ### Help  to  speed up  the trainning process
  ### Help in  memory  usage and cpu usage
  ### Help to  easily visualize the data

## The Curse Of Dimensionality

### 0D To 4D Cubes

![](Dimensionality.png)

In [2]:
#0D - it likes point
#1D - it likes line
#2D - it likes square
# 3D - it linkes cube
# 4D - beyond the 3D, visualization possibility is very low

### How to  do  the dimensionality  reduction
     # Projection
     # Manifold Learning

## Projection

In [3]:
## Projection will not alwaya work

![](swissroledimensionality.png)

## Manifold Leraning

In [4]:
## unroll the swiss role data set we called as Manifold Leraning

![](ManifoldLearning.png)

## Principle Analysis Component(PCA)

In [2]:
### First identify the hyper plane that lies closest to the data1
### Then project the data into this hyper plane

![](3DSwissRole.png)

In [3]:
### Basic idea of the PCA  is preserving the  varience of data

In [5]:
### PCA identify the axis that accounts largest variation of data
###  computer the 2nd axis which is authernagal to the 1st axis


## If you have the higher dimension
       

In [6]:
## PCA find the third axis which is authernagal to the both prevoius axis

## Using the Scikit -Learn
    # Singular value decomposition  - scikit-learn utilize

In [7]:
### VT comprise of all the principles components that we are looking

In [9]:
import numpy as np
np.random.seed(4)
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)
X

array([[-1.01570027, -0.55091331, -0.26132626],
       [-0.00771675,  0.59958572,  0.03507755],
       [-0.95317135, -0.46453691, -0.24920288],
       [-0.92012304,  0.21009593,  0.02182381],
       [-0.76309739,  0.158261  ,  0.19152496],
       [ 1.11816122,  0.32508721,  0.31710572],
       [-1.02258878, -0.64384064, -0.13368695],
       [ 0.67351984, -0.27342519, -0.00787835],
       [ 1.01619558,  0.51546608,  0.46783297],
       [ 0.54957723,  0.67728016,  0.2340159 ],
       [-0.98960443,  0.00886617, -0.12152034],
       [ 1.13248106,  0.28229967,  0.06972972],
       [-0.99337712, -0.26832824, -0.15761101],
       [-0.94763679, -0.4995849 , -0.13927911],
       [ 1.10095709,  0.1706481 ,  0.09790432],
       [-0.34604591,  0.45334414,  0.06433843],
       [ 0.69102621, -0.27337761, -0.05926516],
       [ 0.68302902,  0.70421846,  0.24642318],
       [ 0.8774031 , -0.16775101, -0.02162333],
       [-1.06090127, -0.48213721, -0.38573526],
       [ 0.52336644,  0.66585845,  0.390

In [14]:
from sklearn.decomposition  import PCA
pca= PCA(n_components=2)
X2D=pca.fit_transform(X)


In [12]:
X2D

array([[ 1.26203346,  0.42067648],
       [-0.08001485, -0.35272239],
       [ 1.17545763,  0.36085729],
       [ 0.89305601, -0.30862856],
       [ 0.73016287, -0.25404049],
       [-1.10436914,  0.20204953],
       [ 1.27265808,  0.46781247],
       [-0.44933007,  0.67736663],
       [-1.09356195, -0.04467792],
       [-0.66177325, -0.28651264],
       [ 1.04466138, -0.11244353],
       [-1.05932502,  0.31189109],
       [ 1.13761426,  0.14576655],
       [ 1.16044117,  0.36481599],
       [-1.00167625,  0.39422008],
       [ 0.2750406 , -0.34391089],
       [-0.45624787,  0.69707573],
       [-0.79706574, -0.26870969],
       [-0.66924929,  0.65520024],
       [ 1.30679728,  0.37671343],
       [-0.6626586 , -0.32706423],
       [ 1.25387588,  0.56043928],
       [ 1.04046987, -0.08727672],
       [ 1.26047729,  0.1571074 ],
       [-1.09786649,  0.38643428],
       [-0.7130973 ,  0.64941523],
       [ 0.17786909, -0.43609071],
       [-1.02975735,  0.33747452],
       [ 0.94552283,

In [16]:
### Principles components can find as 
pca.components_

array([[-0.93636116, -0.29854881, -0.18465208],
       [ 0.34027485, -0.90119108, -0.2684542 ]])

In [18]:
pca.components_.T[:,0]

array([-0.93636116, -0.29854881, -0.18465208])

In [20]:
pca.components_.T[:,1]

array([ 0.34027485, -0.90119108, -0.2684542 ])

In [21]:
### varience ratio of the pc

In [22]:
pca.explained_variance_ratio_

array([0.84248607, 0.14631839])

In [23]:
## choosing the right number of dimensions

In [24]:
## compute the PCA without reduce the dim.  then  compute the dimensionality  to preserve the 95%

In [26]:
from  sklearn.datasets import fetch_openml
mnist=fetch_openml('mnist_784', version=1, as_frame=False)
mnist.target=mnist.target.astype(np.uint)

C:\Users\THIS PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\datasets\_openml.py:1022: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [28]:
from  sklearn.model_selection import train_test_split
x= mnist["data"]
y=mnist["target"]


In [29]:
x_train, x_test, y_train,y_test=train_test_split(x,y)

In [32]:
pca=PCA()
pca.fit(x_train)
cumsum=np.cumsum(pca.explained_variance_ratio_)
d= np.argmax(cumsum>=0.95)+1

In [31]:
cumsum

array([0.09719832, 0.16875148, 0.23046024, 0.28447767, 0.33353621,
       0.37656401, 0.40934646, 0.43819275, 0.46567853, 0.48924485,
       0.51032629, 0.5307285 , 0.54778858, 0.56465048, 0.58041792,
       0.59534958, 0.60862878, 0.62147783, 0.63334578, 0.64479193,
       0.65545804, 0.66555448, 0.67514241, 0.68416896, 0.69296211,
       0.70131513, 0.70939893, 0.71727437, 0.72468736, 0.73157212,
       0.73812949, 0.74459959, 0.75058197, 0.75643475, 0.76210811,
       0.7675608 , 0.77261474, 0.77750626, 0.78230885, 0.78696883,
       0.79152081, 0.79597374, 0.80014325, 0.80411726, 0.80795962,
       0.81171266, 0.81533146, 0.81882001, 0.8221978 , 0.82541301,
       0.82859763, 0.83168676, 0.83465474, 0.83752128, 0.84034773,
       0.84303834, 0.84571815, 0.84828932, 0.85083357, 0.85329543,
       0.85569464, 0.8580644 , 0.86035289, 0.86256245, 0.86468703,
       0.86673787, 0.86875875, 0.87071732, 0.87263867, 0.87451472,
       0.87637902, 0.87817437, 0.87993644, 0.88167564, 0.88332

In [33]:
d

154

In [34]:
# 2nd method

In [37]:
pca=PCA(n_components=0.95)
X_reduced=pca.fit_transform(x_train)

In [38]:
X_reduced

array([[-563.82559445,  376.21158523,  547.80926275, ...,   27.55021763,
         -28.99365655,   22.0882605 ],
       [-247.60677317,  594.11581251, -761.17658851, ...,   21.21515701,
         -12.91702701,  -71.9678063 ],
       [ -76.10689476, -718.88626736, -621.34715832, ...,  -15.63703969,
          27.32682087,  -46.49334898],
       ...,
       [ 446.89768572,  200.53844512, -326.08785445, ...,  -16.17022423,
          28.40929801,   53.86153314],
       [ 794.82898692, -164.97878958,   48.41468923, ...,  -51.41226115,
           3.66933099,    7.84388081],
       [-903.11423891, -456.07654002, -139.58512285, ...,    3.89819809,
          58.74804585,    2.75381847]])